# Generated by Django 5.2.7 on 2025-11-07 20:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
