# Generated by Django 5.2.7 on 2025-11-08 08:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
