# Generated by Django 5.2.7 on 2025-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_resume_userprofile_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_image',
        ),
    ]
