# Generated by Django 5.2.7 on 2025-11-15 07:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_address_userprofile_bio_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
