# Generated by Django 5.2.7 on 2025-11-08 20:25

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='image',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_experience',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('1-2', '1-2 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('cv', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cv')),
                ('profile_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_image')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
        ),
    ]
