# Generated by Django 5.2.7 on 2025-11-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobpost_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_title',
            new_name='title',
        ),
    ]
