# Generated by Django 5.2.7 on 2025-11-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='job_title',
        ),
    ]
