# Generated by Django 5.2.7 on 2025-11-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_job_jobapplication_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_title',
            new_name='job',
        ),
    ]
