# Generated by Django 5.2.7 on 2025-11-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_job_title_jobapplication_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job',
            new_name='job_title',
        ),
    ]
