# Generated by Django 5.2.7 on 2025-11-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='is_profane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='profanity_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='spam_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
